create table ulkeler
(
    id   int auto_increment
        primary key,
    code char(2)      null,
    en   varchar(100) null,
    de   varchar(100) null,
    es   varchar(100) null,
    fr   varchar(100) null,
    it   varchar(100) null,
    ru   varchar(100) null,
    tr   varchar(100) null,
    constraint ulkeler2_code_uindex
        unique (code)
)
    charset = utf8;

INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (1, 'AD', 'Andorra', 'Andorra', 'Andorra', 'ANDORRE', 'Andorra ', 'Андорра', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (2, 'AE', 'United Arab Emirates', 'Vereinigte Arabische Emirate', 'Emiratos Árabes Unidos', 'ÉMIRATS ARABES UNIS', 'Emirati Arabi Uniti ', 'ОАЭ', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (3, 'AF', 'Afghanistan', 'Afghanistan', 'Afganistán', 'AFGHANISTAN', 'Afghanistan', 'Афганистан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (4, 'AG', 'Antigua and Barbuda', 'Antigua und Barbuda', 'Antigua y Barbuda', 'ANTIGUA-ET-BARBUDA', 'Antigua e Barbuda', 'Антигуа и Барбуда', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (5, 'AI', 'Anguilla', 'Anguilla', 'Anguila', 'ANGUILLA', 'Anguilla', 'Ангилья', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (6, 'AL', 'Albania', 'Albanien', 'Albania', 'ALBANIE', 'Albania ', 'Албания', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (7, 'AM', 'Armenia', 'Armenien', 'Armenia', 'ARMÉNIE', 'Armenia ', 'Армения', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (8, 'AN', 'Netherlands Antilles', 'Niederländische Antillen', 'Antillas Neerlandesas', '', '', '', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (9, 'AO', 'Angola', 'Angola', 'Angola', 'ANGOLA', 'Angola ', 'Ангола', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (10, 'AQ', 'Antarctica', 'Antarktis', 'Antártida', 'ANTARCTIQUE', 'Antartide ', 'Антарктида', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (11, 'AR', 'Argentina', 'Argentinien', 'Argentina', 'ARGENTINE', 'Argentina ', 'Аргентина', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (12, 'AS', 'American Samoa', 'Amerikanisch-Samoa', 'Samoa Americana', 'SAMOA AMÉRICAINES', 'Samoa Americane', 'Американское Самоа', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (13, 'AT', 'Austria', 'Österreich', 'Austria', 'AUTRICHE', 'Austria', 'Австрия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (14, 'AU', 'Australia', 'Australien', 'Australia', 'AUSTRALIE', 'Australia', 'Австралия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (15, 'AW', 'Aruba', 'Aruba', 'Aruba', 'ARUBA', 'Aruba', 'Аруба', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (16, 'AX', 'Aland Islands', 'Åland', 'Islas Áland', 'ÅLAND, ÎLES', 'Isole Åland', 'Аландские острова', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (17, 'AZ', 'Azerbaijan', 'Aserbaidschan', 'Azerbaiyán', 'AZERBAÏDJAN', 'Azerbaigian', 'Азербайджан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (18, 'BA', 'Bosnia and Herzegovina', 'Bosnien und Herzegowina', 'Bosnia y Herzegovina', 'BOSNIE-HERZÉGOVINE', 'Bosnia ed Erzegovina', 'Босния и Герцеговина', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (19, 'BB', 'Barbados', 'Barbados', 'Barbados', 'BARBADE', 'Barbados', 'Барбадос', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (20, 'BD', 'Bangladesh', 'Bangladesch', 'Bangladesh', 'BANGLADESH', 'Bangladesh', 'Бангладеш', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (21, 'BE', 'Belgium', 'Belgien', 'Bélgica', 'BELGIQUE', 'Belgio', 'Бельгия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (22, 'BF', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'BURKINA FASO', 'Burkina Faso', 'Буркина-Фасо', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (23, 'BG', 'Bulgaria', 'Bulgarien', 'Bulgaria', 'BULGARIE', 'Bulgaria', 'Болгария', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (24, 'BH', 'Bahrain', 'Bahrain', 'Bahréin', 'BAHREÏN', 'Bahrein', 'Бахрейн', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (25, 'BI', 'Burundi', 'Burundi', 'Burundi', 'BURUNDI', 'Burundi', 'Бурунди', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (26, 'BJ', 'Benin', 'Benin', 'Benin', 'BÉNIN', 'Benin', 'Бенин', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (27, 'BM', 'Bermuda', 'Bermuda', 'Bermudas', 'BERMUDES', 'Bermuda', 'Бермуды', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (28, 'BN', 'Brunei', 'Brunei Darussalam', 'Brunéi', 'BRUNÉI DARUSSALAM', 'Brunei', 'Бруней', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (29, 'BO', 'Bolivia', 'Bolivien', 'Bolivia', 'BOLIVIE, ÉTAT PLURINATIONAL DE', 'Bolivia', 'Боливия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (30, 'BR', 'Brazil', 'Brasilien', 'Brasil', 'BRÉSIL', 'Brasile', 'Бразилия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (31, 'BS', 'Bahamas', 'Bahamas', 'Bahamas', 'BAHAMAS', 'Bahamas', 'Багамы', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (32, 'BT', 'Bhutan', 'Bhutan', 'Bhután', 'BHOUTAN', 'Bhutan', 'Бутан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (33, 'BV', 'Bouvet Island', 'Bouvetinsel', 'Isla Bouvet', 'BOUVET, ÎLE', 'Isola Bouvet', 'Остров Буве', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (34, 'BW', 'Botswana', 'Botswana', 'Botsuana', 'BOTSWANA', 'Botswana', 'Ботсвана', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (35, 'BY', 'Belarus', 'Belarus (Weißrussland)', 'Belarús', 'BÉLARUS', 'Bielorussia', 'Белоруссия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (36, 'BZ', 'Belize', 'Belize', 'Belice', 'BELIZE', 'Belize', 'Белиз', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (37, 'CA', 'Canada', 'Kanada', 'Canadá', 'CANADA', 'Canada', 'Канада', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (38, 'CC', 'Cocos (Keeling) Islands', 'Kokosinseln (Keelinginseln)', 'Islas Cocos', 'COCOS (KEELING), ÎLES', 'Isole Cocos (Keeling)', 'Кокосовые острова', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (39, 'CD', 'Congo (Kinshasa)', 'Kongo', 'Congo', 'CONGO, LA RÉPUBLIQUE DÉMOCRATIQUE DU', 'RD del Congo', 'Демократическая Республика Конго', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (40, 'CF', 'Central African Republic', 'Zentralafrikanische Republik', 'República Centro-Africana', 'CENTRAFRICAINE, RÉPUBLIQUE', 'Rep. Centrafricana', 'ЦАР', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (41, 'CG', 'Congo (Brazzaville)', 'Republik Kongo', 'Congo', 'CONGO', 'Rep. del Congo', 'Республика Конго', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (42, 'CH', 'Switzerland', 'Schweiz', 'Suiza', 'SUISSE', 'Svizzera', 'Швейцария', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (43, 'CI', 'Ivory Coast', 'Elfenbeinküste', 'Costa de Marfil', 'CÔTE D’IVOIRE', 'Costa d''Avorio', 'Кот-д’Ивуар', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (44, 'CK', 'Cook Islands', 'Cookinseln', 'Islas Cook', 'COOK, ÎLES', 'Isole Cook', 'Острова Кука', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (45, 'CL', 'Chile', 'Chile', 'Chile', 'CHILI', 'Cile', 'Чили', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (46, 'CM', 'Cameroon', 'Kamerun', 'Camerún', 'CAMEROUN', 'Camerun', 'Камерун', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (47, 'CN', 'China', 'China, Volksrepublik', 'China', 'CHINE', 'Cina', 'КНР (Китайская Народная Республика)', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (48, 'CO', 'Colombia', 'Kolumbien', 'Colombia', 'COLOMBIE', 'Colombia', 'Колумбия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (49, 'CR', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'COSTA RICA', 'Costa Rica', 'Коста-Рика', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (50, 'CU', 'Cuba', 'Kuba', 'Cuba', 'CUBA', 'Cuba', 'Куба', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (51, 'CV', 'Cape Verde', 'Kap Verde', 'Cabo Verde', 'CABO VERDE', 'Capo Verde', 'Кабо-Верде', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (52, 'CX', 'Christmas Island', 'Weihnachtsinsel', 'Islas Christmas', 'CHRISTMAS, ÎLE', 'Isola di Natale', 'Остров Рождества', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (53, 'CY', 'Cyprus', 'Zypern', 'Chipre', 'CHYPRE', 'Cipro', 'Кипр', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (54, 'CZ', 'Czech Republic', 'Tschechische Republik', 'República Checa', 'TCHÈQUE, RÉPUBLIQUE', 'Rep. Ceca', 'Чехия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (55, 'DE', 'Germany', 'Deutschland', 'Alemania', 'ALLEMAGNE', 'Germania', 'Германия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (56, 'DJ', 'Djibouti', 'Dschibuti', 'Yibuti', 'DJIBOUTI', 'Gibuti', 'Джибути', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (57, 'DK', 'Denmark', 'Dänemark', 'Dinamarca', 'DANEMARK', 'Danimarca', 'Дания', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (58, 'DM', 'Dominica', 'Dominica', 'Domínica', 'DOMINIQUE', 'Dominica', 'Доминика', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (59, 'DO', 'Dominican Republic', 'Dominikanische Republik', 'República Dominicana', 'DOMINICAINE, RÉPUBLIQUE', 'Rep. Dominicana', 'Доминиканская Республика', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (60, 'DZ', 'Algeria', 'Algerien', 'Argelia', 'ALGÉRIE', 'Algeria', 'Алжир', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (61, 'EC', 'Ecuador', 'Ecuador', 'Ecuador', 'ÉQUATEUR', 'Ecuador', 'Эквадор', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (62, 'EE', 'Estonia', 'Estland (Reval)', 'Estonia', 'ESTONIE', 'Estonia', 'Эстония', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (63, 'EG', 'Egypt', 'Ägypten', 'Egipto', 'ÉGYPTE', 'Egitto', 'Египет', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (64, 'EH', 'Western Sahara', 'Westsahara', 'Sahara Occidental', 'SAHARA OCCIDENTAL', 'Sahara Occidentale', 'САДР', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (65, 'ER', 'Eritrea', 'Eritrea', 'Eritrea', 'ÉRYTHRÉE', 'Eritrea', 'Эритрея', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (66, 'ES', 'Spain', 'Spanien', 'España', 'ESPAGNE', 'Spagna', 'Испания', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (67, 'ET', 'Ethiopia', 'Äthiopien', 'Etiopía', 'ÉTHIOPIE', 'Etiopia', 'Эфиопия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (68, 'FI', 'Finland', 'Finnland', 'Finlandia', 'FINLANDE', 'Finlandia', 'Финляндия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (69, 'FJ', 'Fiji', 'Fidschi', 'Fiji', 'FIDJI', 'Figi', 'Фиджи', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (70, 'FK', 'Falkland Islands', 'Falklandinseln (Malwinen)', 'Islas Malvinas', 'FALKLAND, ÎLES (MALVINAS)', 'Isole Falkland', 'Фолклендские острова', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (71, 'FM', 'Micronesia', 'Mikronesien', 'Micronesia', 'MICRONÉSIE, ÉTATS FÉDÉRÉS DE', 'Micronesia', 'Микронезия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (72, 'FO', 'Faroe Islands', 'Färöer', 'Islas Faroe', 'FÉROÉ, ÎLES', 'Fær Øer', 'Фареры', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (73, 'FR', 'France', 'Frankreich', 'Francia', 'FRANCE', 'Francia', 'Франция', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (74, 'GA', 'Gabon', 'Gabun', 'Gabón', 'GABON', 'Gabon', 'Габон', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (75, 'GB', 'United Kingdom', 'Großbritannien und Nordirland', 'Reino Unido', 'ROYAUME-UNI', 'Regno Unito', 'Великобритания', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (76, 'GD', 'Grenada', 'Grenada', 'Granada', 'GRENADE', 'Grenada', 'Гренада', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (77, 'GE', 'Georgia', 'Georgien', 'Georgia', 'GÉORGIE', 'Georgia', 'Грузия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (78, 'GF', 'French Guiana', 'Französisch-Guayana', 'Guayana Francesa', 'GUYANE FRANÇAISE', 'Guyana francese', 'Гвиана', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (79, 'GG', 'Guernsey', 'Guernsey (Kanalinsel)', 'Guernsey', 'GUERNESEY', 'Guernsey', 'Гернси', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (80, 'GH', 'Ghana', 'Ghana', 'Ghana', 'GHANA', 'Ghana', 'Гана', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (81, 'GI', 'Gibraltar', 'Gibraltar', 'Gibraltar', 'GIBRALTAR', 'Gibilterra', 'Гибралтар', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (82, 'GL', 'Greenland', 'Grönland', 'Groenlandia', 'GROENLAND', 'Groenlandia', 'Гренландия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (83, 'GM', 'Gambia', 'Gambia', 'Gambia', 'GAMBIE', 'Gambia', 'Гамбия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (84, 'GN', 'Guinea', 'Guinea', 'Guinea', 'GUINÉE', 'Guinea', 'Гвинея', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (85, 'GP', 'Guadeloupe', 'Guadeloupe', 'Guadalupe', 'GUADELOUPE', 'Guadalupa', 'Гваделупа', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (86, 'GQ', 'Equatorial Guinea', 'Äquatorialguinea', 'Guinea Ecuatorial', 'GUINÉE ÉQUATORIALE', 'Guinea Equatoriale', 'Экваториальная Гвинея', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (87, 'GR', 'Greece', 'Griechenland', 'Grecia', 'GRÈCE', 'Grecia ', 'Греция', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (88, 'GS', 'South Georgia and the South Sandwich Islands', 'Südgeorgien und die Südl. Sandwichinseln', 'Georgia del Sur e Islas Sandwich del Sur', 'GÉORGIE DU SUD ET LES ÎLES SANDWICH DU SUD', 'Georgia del Sud e isole Sandwich meridionali', 'Южная Георгия и Южные Сандвичевы Острова', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (89, 'GT', 'Guatemala', 'Guatemala', 'Guatemala', 'GUATEMALA', 'Guatemala', 'Гватемала', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (90, 'GU', 'Guam', 'Guam', 'Guam', 'GUAM', 'Guam', 'Гуам', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (91, 'GW', 'Guinea-Bissau', 'Guinea-Bissau', 'Guinea-Bissau', 'GUINÉE-BISSAU', 'Guinea-Bissau', 'Гвинея-Бисау', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (92, 'GY', 'Guyana', 'Guyana', 'Guayana', 'GUYANA', 'Guyana', 'Гайана', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (93, 'HK', 'Hong Kong S.A.R., China', 'Hongkong', 'Hong Kong', 'HONG KONG', 'Hong Kong', 'Гонконг', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (94, 'HM', 'Heard Island and McDonald Islands', 'Heard- und McDonald-Inseln', 'Islas Heard y McDonald', 'HEARD ET MACDONALD, ÎLES', 'Isole Heard e McDonald', 'Херд и Макдональд', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (95, 'HN', 'Honduras', 'Honduras', 'Honduras', 'HONDURAS', 'Honduras', 'Гондурас', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (96, 'HR', 'Croatia', 'Kroatien', 'Croacia', 'CROATIE', 'Croazia', 'Хорватия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (97, 'HT', 'Haiti', 'Haiti', 'Haití', 'HAÏTI', 'Haiti ', 'Гаити', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (98, 'HU', 'Hungary', 'Ungarn', 'Hungría', 'HONGRIE', 'Ungheria', 'Венгрия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (99, 'ID', 'Indonesia', 'Indonesien', 'Indonesia', 'INDONÉSIE', 'Indonesia', 'Индонезия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (100, 'IE', 'Ireland', 'Irland', 'Irlanda', 'IRLANDE', 'Irlanda ', 'Флаг Ирландии Ирландия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (101, 'IL', 'Israel', 'Israel', 'Israel', 'ISRAËL', 'Israele ', 'Израиль', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (102, 'IM', 'Isle of Man', 'Insel Man', 'Isla de Man', 'ÎLE DE MAN', 'Isola di Man', 'Остров Мэн', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (103, 'IN', 'India', 'Indien', 'India', 'INDE', 'India ', 'Индия Индия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (104, 'IO', 'British Indian Ocean Territory', 'Britisches Territorium im Indischen Ozean', 'Territorio Británico del Océano Índico', 'OCÉAN INDIEN, TERRITOIRE BRITANNIQUE DE L''', 'Territorio britannico dell''oceano', 'Британская территория в Индийском океане', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (105, 'IQ', 'Iraq', 'Irak', 'Irak', 'IRAQ', 'Iraq ', 'Ирак', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (106, 'IR', 'Iran', 'Iran', 'Irán', 'IRAN, RÉPUBLIQUE ISLAMIQUE D''', 'Iran ', 'Иран', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (107, 'IS', 'Iceland', 'Island', 'Islandia', 'ISLANDE', 'Islanda ', 'Исландия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (108, 'IT', 'Italy', 'Italien', 'Italia', 'ITALIE', 'Italia ', 'Италия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (109, 'JE', 'Jersey', 'Jersey (Kanalinsel)', 'Jersey', 'JERSEY', 'Jersey ', 'Джерси', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (110, 'JM', 'Jamaica', 'Jamaika', 'Jamaica', 'JAMAÏQUE', 'Giamaica', 'Ямайка', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (111, 'JO', 'Jordan', 'Jordanien', 'Jordania', 'JORDANIE', 'Giordania ', 'Иордания', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (112, 'JP', 'Japan', 'Japan', 'Japón', 'JAPON', 'Giappone ', 'Япония', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (113, 'KE', 'Kenya', 'Kenia', 'Kenia', 'KENYA', 'Kenya ', 'Кения', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (114, 'KG', 'Kyrgyzstan', 'Kirgisistan', 'Kirguistán', 'KIRGHIZISTAN', 'Kirghizistan', 'Киргизия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (115, 'KH', 'Cambodia', 'Kambodscha', 'Camboya', 'CAMBODGE', 'Cambogia ', 'Камбоджа', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (116, 'KI', 'Kiribati', 'Kiribati', 'Kiribati', 'KIRIBATI', 'Kiribati ', 'Кирибати', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (117, 'KM', 'Comoros', 'Komoren', 'Comoros', 'COMORES', 'Comore ', 'Коморы', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (118, 'KN', 'Saint Kitts and Nevis', 'St. Kitts und Nevis', 'San Cristóbal y Nieves', 'SAINT-KITTS-ET-NEVIS', 'Saint Kitts e Nevis', 'Сент-Китс и Невис', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (119, 'KP', 'North Korea', 'Nordkorea', 'Corea del Norte', 'CORÉE, RÉPUBLIQUE POPULAIRE DÉMOCRATIQUE DE', 'Corea del Nord ', 'КНДР (Корейская Народно-Демократическая Республика)', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (120, 'KR', 'South Korea', 'Südkorea', 'Corea del Sur', 'CORÉE, RÉPUBLIQUE DE', 'Corea del Sud ', 'Республика Корея', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (121, 'KW', 'Kuwait', 'Kuwait', 'Kuwait', 'KOWEÏT', 'Kuwait ', 'Кувейт', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (122, 'KY', 'Cayman Islands', 'Kaimaninseln', 'Islas Caimán', 'CAÏMANES, ÎLES', 'Isole Cayman', 'Острова Кайман', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (123, 'KZ', 'Kazakhstan', 'Kasachstan', 'Kazajstán', 'KAZAKHSTAN', 'Kazakistan ', 'Казахстан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (124, 'LA', 'Laos', 'Laos', 'Laos', 'LAO, RÉPUBLIQUE DÉMOCRATIQUE POPULAIRE', 'Laos ', 'Лаос', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (125, 'LB', 'Lebanon', 'Libanon', 'Líbano', 'LIBAN', 'Libano', 'Ливан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (126, 'LC', 'Saint Lucia', 'St. Lucia', 'Santa Lucía', 'SAINTE-LUCIE', 'Santa Lucia', 'Сент-Люсия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (127, 'LI', 'Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'LIECHTENSTEIN', 'Liechtenstein', 'Лихтенштейн', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (128, 'LK', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'SRI LANKA', 'Sri Lanka ', 'Шри-Ланка', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (129, 'LR', 'Liberia', 'Liberia', 'Liberia', 'LIBÉRIA', 'Liberia ', 'Либерия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (130, 'LS', 'Lesotho', 'Lesotho', 'Lesotho', 'LESOTHO', 'Lesotho ', 'Лесото', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (131, 'LT', 'Lithuania', 'Litauen', 'Lituania', 'LITUANIE', 'Lituania', 'Литва', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (132, 'LU', 'Luxembourg', 'Luxemburg', 'Luxemburgo', 'LUXEMBOURG', 'Lussemburgo', 'Люксембург', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (133, 'LV', 'Latvia', 'Lettland', 'Letonia', 'LETTONIE', 'Lettonia ', 'Латвия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (134, 'LY', 'Libya', 'Libyen', 'Libia', 'LIBYE', 'Libia ', 'Ливия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (135, 'MA', 'Morocco', 'Marokko', 'Marruecos', 'MAROC', 'Marocco', 'Марокко', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (136, 'MC', 'Monaco', 'Monaco', 'Mónaco', 'MONACO', 'Monaco ', 'Монако', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (137, 'MD', 'Moldova', 'Moldawien', 'Moldova', 'MOLDOVA', 'Moldavia', 'Молдавия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (138, 'MG', 'Madagascar', 'Madagaskar', 'Madagascar', 'MADAGASCAR', 'Madagascar ', 'Мадагаскар', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (139, 'MH', 'Marshall Islands', 'Marshallinseln', 'Islas Marshall', 'MARSHALL, ÎLES', 'Isole Marshall', 'Маршалловы Острова', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (140, 'MK', 'Macedonia', 'Mazedonien', 'Macedonia', 'MACÉDOINE, L''EX-RÉPUBLIQUE YOUGOSLAVE DE', 'Macedonia ', 'Македония', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (141, 'ML', 'Mali', 'Mali', 'Mali', 'MALI', 'Mali ', 'Мали', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (142, 'MM', 'Myanmar', 'Myanmar (Burma)', 'Myanmar', 'MYANMAR', 'Birmania', 'Мьянма', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (143, 'MN', 'Mongolia', 'Mongolei', 'Mongolia', 'MONGOLIE', 'Mongolia', 'Монголия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (144, 'MO', 'Macao S.A.R., China', 'Macau', 'Macao', 'MACAO', 'Macao ', 'Макао', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (145, 'MP', 'Northern Mariana Islands', 'Nördliche Marianen', 'Islas Marianas del Norte', 'MARIANNES DU NORD, ÎLES', 'Isole Marianne Settentrionali', 'Северные Марианские острова', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (146, 'MQ', 'Martinique', 'Martinique', 'Martinica', 'MARTINIQUE', 'Martinica', 'Мартиника', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (147, 'MR', 'Mauritania', 'Mauretanien', 'Mauritania', 'MAURITANIE', 'Mauritania', 'Мавритания', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (148, 'MS', 'Montserrat', 'Montserrat', 'Montserrat', 'MONTSERRAT', 'Montserrat', 'Монтсеррат', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (149, 'MT', 'Malta', 'Malta', 'Malta', 'MALTE', 'Malta ', 'Мальта', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (150, 'MU', 'Mauritius', 'Mauritius', 'Mauricio', 'MAURICE', 'Mauritius', 'Маврикий', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (151, 'MV', 'Maldives', 'Malediven', 'Maldivas', 'MALDIVES', 'Maldive ', 'Мальдивы', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (152, 'MW', 'Malawi', 'Malawi', 'Malawi', 'MALAWI', 'Malawi ', 'Малави', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (153, 'MX', 'Mexico', 'Mexiko', 'México', 'MEXIQUE', 'Messico ', 'Мексика', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (154, 'MY', 'Malaysia', 'Malaysia', 'Malasia', 'MALAISIE', 'Malesia ', 'Малайзия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (155, 'MZ', 'Mozambique', 'Mosambik', 'Mozambique', 'MOZAMBIQUE', 'Mozambico', 'Мозамбик', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (156, 'NA', 'Namibia', 'Namibia', 'Namibia', 'NAMIBIE', 'Namibia ', 'Намибия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (157, 'NC', 'New Caledonia', 'Neukaledonien', 'Nueva Caledonia', 'NOUVELLE-CALÉDONIE', 'Nuova Caledonia', 'Новая Каледония', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (158, 'NE', 'Niger', 'Niger', 'Níger', 'NIGER', 'Niger ', 'Нигер', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (159, 'NF', 'Norfolk Island', 'Norfolkinsel', 'Islas Norkfolk', 'NORFOLK, ÎLE', 'Isola Norfolk', 'Остров Норфолк', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (160, 'NG', 'Nigeria', 'Nigeria', 'Nigeria', 'NIGÉRIA', 'Nigeria ', 'Нигерия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (161, 'NI', 'Nicaragua', 'Nicaragua', 'Nicaragua', 'NICARAGUA', 'Nicaragua', 'Никарагуа', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (162, 'NL', 'Netherlands', 'Niederlande', 'Países Bajos', 'PAYS-BAS', 'Paesi Bassi', 'Нидерланды', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (163, 'NO', 'Norway', 'Norwegen', 'Noruega', 'NORVÈGE', 'Norvegia ', 'Норвегия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (164, 'NP', 'Nepal', 'Nepal', 'Nepal', 'NÉPAL', 'Nepal ', 'Непал', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (165, 'NR', 'Nauru', 'Nauru', 'Nauru', 'NAURU', 'Nauru ', 'Науру', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (166, 'NU', 'Niue', 'Niue', 'Niue', 'NIUÉ', 'Niue ', 'Ниуэ', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (167, 'NZ', 'New Zealand', 'Neuseeland', 'Nueva Zelanda', 'NOUVELLE-ZÉLANDE', 'Nuova Zelanda', 'Новая Зеландия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (168, 'OM', 'Oman', 'Oman', 'Omán', 'OMAN', 'Oman ', 'Оман', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (169, 'PA', 'Panama', 'Panama', 'Panamá', 'PANAMA', 'Panamá', 'Панама', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (170, 'PE', 'Peru', 'Peru', 'Perú', 'PÉROU', 'Perù ', 'Перу', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (171, 'PF', 'French Polynesia', 'Französisch-Polynesien', 'Polinesia Francesa', 'POLYNÉSIE FRANÇAISE', 'Polinesia Francese ', 'Французская Полинезия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (172, 'PG', 'Papua New Guinea', 'Papua-Neuguinea', 'Papúa Nueva Guinea', 'PAPOUASIE-NOUVELLE-GUINÉE', 'Papua Nuova Guinea ', 'Папуа — Новая Гвинея', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (173, 'PH', 'Philippines', 'Philippinen', 'Filipinas', 'PHILIPPINES', 'Filippine ', 'Филиппины', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (174, 'PK', 'Pakistan', 'Pakistan', 'Pakistán', 'PAKISTAN', 'Pakistan ', 'Пакистан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (175, 'PL', 'Poland', 'Polen', 'Polonia', 'POLOGNE', 'Polonia ', 'Польша', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (176, 'PM', 'Saint Pierre and Miquelon', 'St. Pierre und Miquelon', 'San Pedro y Miquelón', 'SAINT-PIERRE-ET-MIQUELON', 'Saint-Pierre e Miquelon', 'Сен-Пьер и Микелон', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (177, 'PN', 'Pitcairn', 'Pitcairninseln', 'Islas Pitcairn', 'PITCAIRN', 'Isole Pitcairn ', 'Острова Питкэрн', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (178, 'PR', 'Puerto Rico', 'Puerto Rico', 'Puerto Rico', 'PORTO RICO', 'Porto Rico ', 'Пуэрто-Рико', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (179, 'PS', 'Palestine', 'Palästina', 'Palestina', 'ÉTAT DE PALESTINE', 'Palestina ', 'Государство Палестина', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (180, 'PT', 'Portugal', 'Portugal', 'Portugal', 'PORTUGAL', 'Portogallo ', 'Португалия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (181, 'PW', 'Palau', 'Palau', 'Islas Palaos', 'PALAOS', 'Palau ', 'Палау', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (182, 'PY', 'Paraguay', 'Paraguay', 'Paraguay', 'PARAGUAY', 'Paraguay ', 'Парагвай', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (183, 'QA', 'Qatar', 'Katar', 'Qatar', 'QATAR', 'Qatar ', 'Катар', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (184, 'RE', 'Reunion', 'Réunion', 'Reunión', 'RÉUNION', 'Riunione ', 'Реюньон', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (185, 'RO', 'Romania', 'Rumänien', 'Rumanía', 'ROUMANIE', 'Romania ', 'Румыния', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (186, 'RU', 'Russia', 'Russische Föderation', 'Rusia', 'RUSSIE, FÉDÉRATION DE', 'Russia ', 'Россия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (187, 'RW', 'Rwanda', 'Ruanda', 'Ruanda', 'RWANDA', 'Ruanda ', 'Руанда', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (188, 'SA', 'Saudi Arabia', 'Saudi-Arabien', 'Arabia Saudita', 'ARABIE SAOUDITE', 'Arabia Saudita', 'Саудовская Аравия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (189, 'SB', 'Solomon Islands', 'Salomonen', 'Islas Solomón', 'SALOMON, ÎLES', 'Isole Salomone', 'Соломоновы Острова', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (190, 'SC', 'Seychelles', 'Seychellen', 'Seychelles', 'SEYCHELLES', 'Seychelles', 'Сейшельские Острова', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (191, 'SD', 'Sudan', 'Sudan', 'Sudán', 'SOUDAN', 'Sudan ', 'Судан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (192, 'SE', 'Sweden', 'Schweden', 'Suecia', 'SUÈDE', 'Svezia', 'Швеция', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (193, 'SG', 'Singapore', 'Singapur', 'Singapur', 'SINGAPOUR', 'Singapore', 'Сингапур', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (194, 'SH', 'Saint Helena', 'St. Helena', 'Santa Elena', 'SAINTE-HÉLÈNE, ASCENSION ET TRISTAN DA CUNHA', 'Sant''Elena, Ascensione e Tristan da Cunha', 'Острова Святой Елены, Вознесения и Тристан-да-Кунья', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (195, 'SI', 'Slovenia', 'Slowenien', 'Eslovenia', 'SLOVÉNIE', 'Slovenia Slovenia', 'Словения', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (196, 'SJ', 'Svalbard and Jan Mayen', 'Svalbard und Jan Mayen', 'Islas Svalbard y Jan Mayen', 'SVALBARD ET ÎLE JAN MAYEN', 'Svalbard e Jan Mayen', 'Флаг Шпицбергена и Ян-Майена Шпицберген и Ян-Майен', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (197, 'SK', 'Slovakia', 'Slowakei', 'Eslovaquia', 'SLOVAQUIE', 'Slovacchia ', 'Словакия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (198, 'SL', 'Sierra Leone', 'Sierra Leone', 'Sierra Leona', 'SIERRA LEONE', 'Sierra Leone', 'Сьерра-Леоне', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (199, 'SM', 'San Marino', 'San Marino', 'San Marino', 'SAINT-MARIN', 'San Marino ', 'Сан-Марино', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (200, 'SN', 'Senegal', 'Senegal', 'Senegal', 'SÉNÉGAL', 'Senegal ', 'Сенегал', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (201, 'SO', 'Somalia', 'Somalia', 'Somalia', 'SOMALIE', 'Somalia ', 'Сомали', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (202, 'SR', 'Suriname', 'Suriname', 'Surinam', 'SURINAME', 'Suriname', 'Суринам', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (203, 'ST', 'Sao Tome and Principe', 'São Tomé und Príncipe', 'Santo Tomé y Príncipe', 'SAO TOMÉ-ET-PRINCIPE', 'São Tomé e Príncipe', 'Сан-Томе и Принсипи', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (204, 'SV', 'El Salvador', 'El Salvador', 'El Salvador', 'EL SALVADOR', 'El Salvador ', 'Сальвадор', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (205, 'SY', 'Syria', 'Syrien', 'Siria', 'SYRIENNE, RÉPUBLIQUE ARABE', 'Siria ', 'Сирия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (206, 'SZ', 'Swaziland', 'Swasiland', 'Suazilandia', 'SWAZILAND', 'Swaziland', 'Свазиленд', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (207, 'TC', 'Turks and Caicos Islands', 'Turks- und Caicosinseln', 'Islas Turcas y Caicos', 'TURKS ET CAÏQUES, ÎLES', 'Turks e Caicos ', 'Тёркс и Кайкос', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (208, 'TD', 'Chad', 'Tschad', 'Chad', 'TCHAD', 'Ciad ', 'Чад', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (209, 'TF', 'French Southern Territories', 'Französische Süd- und Antarktisgebiete', 'Territorios Australes Franceses', 'TERRES AUSTRALES FRANÇAISES', 'Terre australi e antartiche francesi', 'Французские Южные и Антарктические Территории', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (210, 'TG', 'Togo', 'Togo', 'Togo', 'TOGO', 'Togo ', 'Того', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (211, 'TH', 'Thailand', 'Thailand', 'Tailandia', 'THAÏLANDE', 'Thailandia', 'Таиланд', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (212, 'TJ', 'Tajikistan', 'Tadschikistan', 'Tayikistán', 'TADJIKISTAN', 'Tagikistan', 'Таджикистан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (213, 'TK', 'Tokelau', 'Tokelau', 'Tokelau', 'TOKELAU', 'Tokelau ', 'Токелау', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (214, 'TL', 'East Timor', 'Timor-Leste', 'Timor-Leste', 'TIMOR-LESTE', 'Timor Est', 'Восточный Тимор', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (215, 'TM', 'Turkmenistan', 'Turkmenistan', 'Turkmenistán', 'TURKMÉNISTAN', 'Turkmenistan', 'Туркмения', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (216, 'TN', 'Tunisia', 'Tunesien', 'Túnez', 'TUNISIE', 'Tunisia ', 'Тунис', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (217, 'TO', 'Tonga', 'Tonga', 'Tonga', 'TONGA', 'Tonga ', 'Тонга', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (218, 'TR', 'Turkey', 'Türkei', 'Turquía', 'TURQUIE', 'Turchia', 'Турция', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (219, 'TT', 'Trinidad and Tobago', 'Trinidad und Tobago', 'Trinidad y Tobago', 'TRINITÉ-ET-TOBAGO', 'Trinidad e Tobago', 'Тринидад и Тобаго', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (220, 'TV', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'TUVALU', 'Tuvalu ', 'Тувалу', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (221, 'TW', 'Taiwan', 'Taiwan', 'Taiwán', 'TAÏWAN, PROVINCE DE CHINE', 'Taiwan ', 'Китайская Республика', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (222, 'TZ', 'Tanzania', 'Tansania', 'Tanzania', 'TANZANIE, RÉPUBLIQUE UNIE DE', 'Tanzania ', 'Танзания', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (223, 'UA', 'Ukraine', 'Ukraine', 'Ucrania', 'UKRAINE', 'Ucraina ', 'Украина', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (224, 'UG', 'Uganda', 'Uganda', 'Uganda', 'OUGANDA', 'Uganda ', 'Уганда', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (225, 'UM', 'United States Minor Outlying Islands', 'Amerikanisch-Ozeanien', 'Islas menores periféricas de los Estados Unidos', 'ÎLES MINEURES ÉLOIGNÉES DES ÉTATS-UNIS', 'Isole minori esterne degli Stati Uniti', 'Внешние малые острова (США)', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (226, 'US', 'United States', 'Vereinigte Staaten von Amerika', 'Estados Unidos de América', 'ÉTATS-UNIS', 'Stati Uniti', 'США', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (227, 'UY', 'Uruguay', 'Uruguay', 'Uruguay', 'URUGUAY', 'Uruguay ', 'Уругвай', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (228, 'UZ', 'Uzbekistan', 'Usbekistan', 'Uzbekistán', 'OUZBÉKISTAN', 'Uzbekistan', 'Узбекистан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (229, 'VA', 'Vatican', 'Vatikanstadt', 'Ciudad del Vaticano', 'SAINT-SIÈGE (ÉTAT DE LA CITÉ DU VATICAN)', 'Città del Vaticano', 'Ватикан', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (230, 'VC', 'Saint Vincent and the Grenadines', 'St. Vincent und die Grenadinen', 'San Vicente y las Granadinas', 'SAINT-VINCENT-ET-LES-GRENADINES', 'Saint Vincent e Grenadine', 'Сент-Винсент и Гренадины', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (231, 'VE', 'Venezuela', 'Venezuela', 'Venezuela', 'VENEZUELA, RÉPUBLIQUE BOLIVARIENNE DU', 'Venezuela ', 'Венесуэла', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (232, 'VG', 'British Virgin Islands', 'Britische Jungferninseln', 'Islas Vírgenes Británicas', 'ÎLES VIERGES BRITANNIQUES', 'Isole Vergini britanniche ', 'Британские Виргинские острова', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (233, 'VI', 'U.S. Virgin Islands', 'Amerikanische Jungferninseln', 'Islas Vírgenes de los Estados Unidos de América', 'ÎLES VIERGES DES ÉTATS-UNIS', 'Isole Vergini americane ', 'Виргинские Острова (США)', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (234, 'VN', 'Vietnam', 'Vietnam', 'Vietnam', 'VIET NAM', 'Vietnam', 'Вьетнам', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (235, 'VU', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'VANUATU', 'Vanuatu', 'Вануату', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (236, 'WF', 'Wallis and Futuna', 'Wallis und Futuna', 'Wallis y Futuna', 'WALLIS-ET-FUTUNA', 'Wallis e Futuna', 'Уоллис и Футуна', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (237, 'WS', 'Samoa', 'Samoa', 'Samoa', 'SAMOA', 'Samoa ', 'Самоа', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (238, 'YE', 'Yemen', 'Jemen', 'Yemen', 'YÉMEN', 'Yemen ', 'Йемен', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (239, 'YT', 'Mayotte', 'Mayotte', 'Mayotte', 'MAYOTTE', 'Mayotte ', 'Майотта', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (240, 'ZA', 'South Africa', 'Südafrika', 'Sudáfrica', 'AFRIQUE DU SUD', 'Sudafrica ', 'ЮАР', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (241, 'ZM', 'Zambia', 'Sambia', 'Zambia', 'ZAMBIE', 'Zambia ', 'Замбия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (242, 'ZW', 'Zimbabwe', 'Simbabwe', 'Zimbabue', 'ZIMBABWE', 'Zimbabwe', 'Зимбабве', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (243, 'RS', 'Serbia', 'Serbien', 'Serbia', 'SERBIE', 'Serbia ', 'Сербия', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (244, 'ME', 'Montenegro', 'Montenegro', 'Montenegro', 'MONTÉNÉGRO', 'Montenegro', 'Черногория', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (245, 'BL', 'Saint Barthelemy !Saint Barthélemy', 'Saint-Barthélemy', 'Saint Barthélemy', 'SAINT-BARTHÉLEMY', 'Saint-Barthélemy', 'Сен-Бартелеми', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (246, 'BQ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius und Saba', 'Bonaire, San Eustaquio y Saba', 'BONAIRE, SAINT-EUSTACHE ET SABA', 'Isole BES', 'Синт-Эстатиус и Саба', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (247, 'CW', 'Curacao !Curaçao', 'Curaçao', 'Curaçao', 'CURAÇAO', 'Curaçao', 'Кюрасао', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (248, 'MF', 'Saint Martin (French part)', 'Saint-Martin (franz. Teil)', 'Saint Martin (parte francesa)', 'SAINT-MARTIN (PARTIE FRANÇAISE)', 'Saint-Martin', 'Сен-Мартен', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (249, 'SX', 'Sint Maarten (Dutch part)', 'Sint Maarten (niederl. Teil)', 'Sint Maarten (parte neerlandesa)', 'SAINT-MARTIN (PARTIE NÉERLANDAISE)', 'Sint Maarten ', 'Синт-Мартен', null);
INSERT INTO ulkeler (id, code, en, de, es, fr, it, ru, tr) VALUES (250, 'SS', 'South Sudan', 'Sudsudan!Südsudan', 'Sudán del Sur', 'SOUDAN DU SUD', 'Sudan del Sud', 'Южный Судан', null);